config/routes.rb
ProjectMain::Application.routes.draw do

  resources :categories

  resources :orders

  resources :line_items
  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :quotations, only: [:new, :create, :destroy, :show]
  resources :contractors, only: [:new, :create, :destroy, :update, :edit, :show]

  root :to => 'projectmain#home'
  match '/signup', to: 'users#new'
  match '/show', to: 'users#show'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signin', to:'sessions#new'
  match '/sessions', to: 'sessions#new' # delete this after merge
  match '/quotations', to:'quotations#new'
  match '/store/index', to: 'store#index', as: 'store'
  match '/your_cart', to: 'carts#your_cart', as: 'your_cart'
  match '/contractors', to: 'contractors#new'
  match '/display_all', to: 'contractors#show'
  match '/display_edit', to: 'contractors#edit'
  match '/thankyou', to: 'projectmain#thank_you'
  match '/product_new', to: 'products#new'
  match '/show_all',  to: 'users#show_all'
  match '/soldering', to: 'categories#show', :id => '2'
  match '/tiling', to: 'categories#show', :id => '3'
  match '/decking', to: 'categories#show', :id => '4'

end

app/controllers/projectmain_controller.rb
class ProjectmainController < ApplicationController
  def home
  end
end

app/helpers/projectmain_helper.rb
module ProjectmainHelper
end

app/views/projectmain/home.html.erb
<!--<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">-->

<head>
  <title>DIY or NOT</title>
  </head>
<body>
<div id="diyhead">
<h1> D<span style=font-size:.75em>o</span> I<span style=font-size:.75em>t</span> Y<span style=font-size:.75em>ourself</span>
          or NOT</h1>
</div>
<p> We aim to solve any of your DIY problems,
  from soldering to plumbing.<br/>  Let us show you how the work should be
  done.<br/>  We can provide the tools you need for the job,<br/>or we can put
  you in touch with a reputable tradesperson who can do the job for you.</p>






<div id="Leftcolumn">

 <ul>
    <li>Soldering</li>
    <ul>
      <li><a href="http://www.youtube.com/embed/lPMHJOgm76M" target="source">"How To" video</a></li>
      <li><%= link_to "Required Tools", soldering_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Request a Quotation", quotations_path %></li>
          <% end %>
    </ul>


 </ul>
  <ul>
    <li>Tiling</li>
    <ul>
      <li> <a href="http://www.youtube.com/embed/LbPO8shSPoU" target="source">"How To" video</a></li>
      <li><%= link_to "Required Tools", tiling_path %></li>
      <% if signed_in? %>
          <li><%= link_to "Request a Quotation", quotations_path %></li>
      <% end %>

    </ul>
    </ul>

  <ul>
    <li>Decking</li>
    <ul>
      <li><a href="http://www.youtube.com/embed/SNr4ysLaMcc" target="source">"How To" video</a></li>
      <li><%= link_to "Required Tools", decking_path %></li>
      <% if signed_in? %>
          <li><%= link_to "Request a Quotation", quotations_path %></li>
      <% end %>

    </ul>
  </ul>

    </div>

</div>
<div id ="Rightcolumn">
  <table class="table_id">
    <tr>
      <td><iframe name="source" src="http://www.youtube.com/embed/lORIZ1shRIM" width="600px" height="400px"></iframe>
      </td>

    </tr>
  </table>
</div>



</body>
</html>

app/views/projectmain/thank_you.erb
<!--<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">-->

<head>
  <title>DIY or NOT</title>
</head>
<body>
<h3> Thank you for your order </h3><br/>
<p>We appreciate your business.  Your order will ship within 1-2 working days.
</p><br/>






<p>Click<%= link_to 'here', root_path %>to return to our Home Page</p>







</body>
</html>