config/routes.rb
ProjectMain::Application.routes.draw do

  resources :categories

  resources :orders

  resources :line_items
  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :quotations, only: [:new, :create, :destroy, :show]
  resources :contractors, only: [:new, :create, :destroy, :update, :edit, :show]

  root :to => 'projectmain#home'
  match '/signup', to: 'users#new'
  match '/show', to: 'users#show'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signin', to:'sessions#new'
  match '/sessions', to: 'sessions#new' # delete this after merge
  match '/quotations', to:'quotations#new'
  match '/store/index', to: 'store#index', as: 'store'
  match '/your_cart', to: 'carts#your_cart', as: 'your_cart'
  match '/contractors', to: 'contractors#new'
  match '/display_all', to: 'contractors#show'
  match '/display_edit', to: 'contractors#edit'
  match '/thankyou', to: 'projectmain#thank_you'
  match '/product_new', to: 'products#new'
  match '/show_all',  to: 'users#show_all'
  match '/soldering', to: 'categories#show', :id => '2'
  match '/tiling', to: 'categories#show', :id => '3'
  match '/decking', to: 'categories#show', :id => '4'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :user

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController


  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end

  def your_cart
    redirect_to :action => "show", :id => current_cart.id
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url,
                                notice: 'Your basket is currently empty' }
      format.json { head :ok }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title">Order Details:</div>
<table>
<!-- START_HIGHLIGHT -->
  <%= render(cart.line_items) %>
<!-- END_HIGHLIGHT -->

  <tr class="total_line">
    <td colspan="2">Total</td>
<!-- START_HIGHLIGHT -->
    <td class="total_cell"><%= number_to_currency(cart.total_price, :unit => '&euro;') %></td>
    <td><%= button_to 'Empty cart', cart, method: :delete,
            #END_HIGHLIGHT
            confirm: 'Are you sure?' %></td>
<!-- END_HIGHLIGHT -->
  </tr>

</table>

<!-- START_HIGHLIGHT -->

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th>Cart ID</th>
    <th>User ID</th>
    <th>Date Created</th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= cart.id %></td>
    <td><%= cart.user_id %></td>
    <td><%= cart.created_at %></td>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="cart_title">Your Basket</div>
<table>
  <% @cart.line_items.each do |item| %>
      <tr>
        <td><%= item.quantity %>&times;</td>
        <td><%= item.product.title %></td>
        <td class="item_price"><%= number_to_currency(item.total_price, :unit => '&euro;') %></td>
      </tr>
  <% end %>
  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"><%= number_to_currency(@cart.total_price, :unit => '&euro;') %></td>
  </tr>
</table>
<!-- START_HIGHLIGHT -->
<p></p>
<%= button_to "Continue Shopping", store_path %>
<%= button_to "Checkout", new_order_path, method: :get %>

<!-- END_HIGHLIGHT -->
<%= button_to 'Empty Basket', @cart, method: :delete,
    confirm: 'Are you sure?' %>